# .goreleaser.yml
#
# A specific config for homebrew releases
# that cannot be run using Github Actions.
#
# test the config:
# goreleaser check
# goreleaser release --skip-publish --skip-validate --rm-dist

before:
  hooks:
    - go mod tidy
builds:
  - id: macOS
    binary: myip
    goos: ['darwin']
    goarch: ['amd64', 'arm64']
    dir: ./../

archives:
  - id: macOS
    builds: ['macOS']
    format: tar.gz
    files:
    - none*
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    replacements:
      arm64: M-series
      amd64: Intel
      darwin: macOS

release:
  github:
    owner: bengarrett
    name: homebrew-myip

brews:
  -
    ids: ['macOS']

    tap:
      owner: bengarrett
      name: myip

    # Your app's homepage.
    homepage: "https://github.com/bengarrett/myip/"

    # Your app's description.
    description: "Determine your Internet-facing IP address and location from multiple sources."

    # SPDX identifier of your app's license.
    license: "MIT"

    install: |
      bin.install "myip"