# .goreleaser.yml
#
# A specific config for homebrew releases that cannot be run as a Github Action.
#
# Instructions:
# 1) Push all changes to the bengarrett/myip.
# 2) On github publish a new release tag and let the Github Action finish.
# 3) In a local terminal do the following:
#
# cd github/myip
# git pull
# export GITHUB_TOKEN="YOUR_GH_TOKEN"
# goreleaser release --skip-validate --rm-dist --config .brew/.goreleaser.yml
#
# To test the config:
# goreleaser check
# goreleaser release --skip-publish --skip-validate --rm-dist

before:
  hooks:
    - go mod tidy
builds:
  - id: macOS
    binary: myip
    goos: ['darwin']
    goarch: ['amd64', 'arm64']
    dir: ./

archives:
  - id: macOS
    builds: ['macOS']
    format: tar.gz
    files:
    - none*
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    replacements:
      arm64: M-series
      amd64: Intel
      darwin: macOS

universal_binaries:
  - id: macOS
    name_template: myip
    replace: true

release:
  github:
    owner: bengarrett
    name: homebrew-myip

brews:
  -
    name: myip
    ids: ['macOS']

    tap:
      owner: bengarrett
      name: homebrew-myip

    # Your app's homepage.
    homepage: "https://github.com/bengarrett/myip/"

    # Your app's description.
    description: "Determine your Internet-facing IP address and location from multiple sources."

    # SPDX identifier of your app's license.
    license: "MIT"

    test: |
      system "#{bin}/myip --version"

    install: |
      bin.install "myip"