# golangci-lint run
#
# Fixes
# gofumpt -l -w <file>
# gci -w <file>

linters:
  enable-all: true
  disable:
    - depguard # not needed
    - exhaustruct # not needed
    - exportloopref # no longer relevant
    - forbidigo # forbids the use for fmt.Print(f|ln)
    - nlreturn # opinionated
    - paralleltest # causes tests to randomly fail
    #    - testpackage # removes the ability to test internal functions
    - varnamelen # doesn't allow short var names for flags
    - wrapcheck # wrapping 3rd party errors such as those from bolt are unnecessary
    - wsl # whitespace linter, slow, aggressive and opinionated

linters-settings:
  cyclop:
    # the maximal code complexity to report
    max-complexity: 15
