# .goreleaser.yml
#
# test the config:
# goreleaser check
# goreleaser release --skip-publish --skip-validate --rm-dist

builds:
  - id: Linux Intel
    goos: ['linux']
    goarch: ['amd64']
  - id: Linux arm
    goos: ['linux']
    goarch: ['arm', 'arm64']
  - id: macOS
    goos: ['darwin']
    goarch: ['amd64', 'arm64']
  - id: Windows
    goos: ['windows']
    goarch: ['amd64']

archives:
  - id: Linux Intel
    builds: ['Linux Intel']
    format: tar.gz
    files:
    - none*
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    replacements:
      amd64: Intel
      linux: Linux
  - id: Linux arm
    builds: ['Linux arm']
    format: tar.gz
    files:
    - none*
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    replacements:
      arm: arm32_
      arm64: arm64
      linux: Linux
  - id: macOS
    builds: ['macOS']
    format: tar.gz
    files:
    - none*
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    replacements:
      arm64: M-series
      amd64: Intel
      darwin: macOS
  - id: Windows
    builds: ['Windows']
    format: zip
    files:
    - none*
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    replacements:
      amd64: Intel
      windows: Windows

nfpms:
  - id: Linux
    builds: ['Linux Intel']
    file_name_template: "{{ .ProjectName }}"
    replacements:
      amd64: Intel
      linux: Linux
    vendor: Ben Garrett.
    homepage: https://github.com/bengarrett/myip
    maintainer: Ben Garrett <code.by.ben@gmail.com>
    description: Determine your Internet-facing IP address and location from multiple sources.
    license: MIT License
    formats:
      - apk
      - deb
      - rpm