# .goreleaser.yml
#
# test the config:
# goreleaser check
# goreleaser release --skip=publish --skip=validate --clean

version: 2

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/myip
    id: FreeBSD
    goos: ["freebsd"]
    goarch: ["amd64"]
  - main: ./cmd/myip
    id: Linux_Intel
    goos: ["linux"]
    goarch: ["amd64"]
  - main: ./cmd/myip
    id: Linux_arm64
    goos: ["linux"]
    goarch: ["arm", "arm64"]
  - main: ./cmd/myip
    id: macOS
    goos: ["darwin"]
    goarch: ["amd64", "arm64"]
  - main: ./cmd/myip
    id: Windows
    goos: ["windows"]
    goarch: ["amd64"]
universal_binaries:
  - id: macOS
    name_template: "{{ .ProjectName }}"
    replace: true

archives:
  - id: FreeBSD
    builds: ['BSD']
    format: tar.gz
    files:
    - none*
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
  - id: Linux_Intel
    builds: ['Linux_Intel']
    format: tar.gz
    files:
    - none*
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
  - id: Linux_arm64
    builds: ['Linux_arm64']
    format: tar.gz
    files:
    - none*
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
  - id: macOS
    builds: ['macOS']
    format: tar.gz
    files:
    - none*
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
  - id: Windows
    builds: ['Windows']
    format: zip
    files:
    - none*
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

nfpms:
  - id: Linux
    builds: ['Linux_Intel']
    file_name_template: "{{ .ProjectName }}"
    vendor: Ben Garrett.
    homepage: https://github.com/bengarrett/myip
    maintainer: Ben Garrett <code.by.ben@gmail.com>
    description: Determine your Internet-facing IP address and location from multiple sources.
    license: MIT License
    formats:
      - apk
      - deb
      - rpm
      - archlinux
