# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HomebrewMyip < Formula
  desc "Determine your Internet-facing IP address and location from multiple sources."
  homepage "https://github.com/bengarrett/myip/"
  version "0.9.2-fix6"
  license "MIT"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/bengarrett/homebrew-myip/releases/download/v0.9.2-fix6/homebrew-myip_macOS_Intel.tar.gz"
    sha256 "374d982c8cd93134fdf9ee6eef397c28980472a54defef39e145d8e5292a4e01"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/bengarrett/homebrew-myip/releases/download/v0.9.2-fix6/homebrew-myip_macOS_M-series.tar.gz"
    sha256 "24a01cc28900eeefe76f4cd39f692ec5d6acb0f43f85d1518705c9bc41cb3222"
  end

  def install
    bin.install "myip"
  end
end
